### ISSUE TITLE
Update with the current Married without Delay form

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MarriageWithoutDelay#24]
- [ ] Determine whether the substantive law change @nonprofittechy referenced in [this comment](https://github.com/SuffolkLITLab/docassemble-MarriageWithoutDelay/issues/24#issuecomment-1964472970) requires an update to the interview.
- [ ] Update the interview to use the [current Marriage without Delay form](https://www.mass.gov/media/885771/download) found by @ctolosatomassini after double-checking to make sure that is the most current form.

**Comment by nonprofittechy** [comment]
@ctolosatomassini is this because the marriage without delay no longer applies to minors? Do you have the new form handy by any chance?

**Comment by ctolosatomassini** [comment]
@nonprofittechy Yes! When you look up the form required for Marriage without Delay for MA, the form is different.  See https://www.mass.gov/media/885771/download
