### ISSUE TITLE
Add an automated test

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MarriageWithoutDelay#25]
Use the [Kiln](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing) framework to add at least one automated test to this repository

**Comment by ctolosatomassini** [comment]
[variables.json](https://github.com/SuffolkLITLab/docassemble-MarriageWithoutDelay/files/14284347/variables.json)
