### ISSUE TITLE
MVP? Find out: requirements of District v. Family & Probate

### ISSUE THREAD

**Issue by mpmilward** [SuffolkLITLab/docassemble-MarriageWithoutDelay#5]
Make sure you can file for Marriage without Delay in both district and probate & family court during the pandemic. At other times, it is possible to file in both district and probate & family court. The PDF is a form sent from probate & family court. If the user is filing in a district court, we need to determine if a different form from the district court is required. If not, should the name of the form, "Family & Probate", be replaced with "District"?

**Comment by testplocket** [comment]
Emailed with SME Katie Milton 8/9 - Same form can be used in District Court and Probate and Family Court. She stated that she had to confer with someone who worked at the courts to be sure

**Comment by aubsticle** [comment]
Emailed with SME Katie Milton 8/9 - Confirmed same form can be used in District Court and Probate and Family Court. Katie provided answer after conferring with someone who worked at the courts to be sure
